#! /usr/bin/env bash

test_break="______________________________________________________________________"

location_error() {
  echo -n "You should execute the tests from the root of the (cloned) "
  echo "romaine git repository."
  exit 1
}

if [[ ! -d src/romaine ]]; then
  echo -n "Cannot find Romaine source files in src/romaine."
  location_error
fi

if [[ ! -d tests ]]; then
  echo "Cannot find tests directory."
  location_error
fi

echo "Running tests."
find tests -name 'test_*' -executable -print -exec sh -c "{} ; echo ${test_break} " \;

# Blank line for formatting
echo ""

if ! which flake8 >/dev/null; then
  echo "Flake8 not present, cannot run code quality checker."
  echo "You should: pip install flake8"
  exit 1
fi

rm -f .romaine_code_quality_error
echo "Checking tests code quality..."
find tests -name '*.py' -exec bash -c 'flake8 {} || touch .romaine_code_quality_error' \;
if [[ -f .romaine_code_quality_error ]]; then
  echo "...errors found."
  echo "ERROR: Please correct errors listed above before running again."
  exit 1
else
  echo "...code quality tests complete. No errors found."
fi

# Blank line for formatting
echo ""

echo "Checking Romaine core code quality..."
find src/romaine -name '*.py' -exec bash -c 'flake8 {} || touch .romaine_code_quality_error' \;
if [[ -f .romaine_code_quality_error ]]; then
  echo "...errors found."
  echo "ERROR: Please correct errors listed above before running again."
  exit 1
else
  echo "...code quality tests complete. No errors found."
fi
